---
title: 'Introducing fmlr: A Novel High-Performance Matrix Framework for R'
author: "Drew Schmidt"
date: "12/15/2021"
output:
  rmarkdown::github_document
bibliography: references.bib
csl: ieee.csl
---

Out-of-the-box, R contains a wealth of matrix operations, mostly in support of numerical computing on double precision data. There are also numerous package extensions extending this core interface to additional kinds of data, from the well-known Matrix package @Matrix, to the gpuR packages @gpur for GPGPU, and of course far too many others to name here. These extensions are generally focused on solving one particular problem; for example, how do we do matrix computing from R on a GPU?

Most of these kinds of matrix extensions operate at the R level. As such, they will almost always go out of their way to integrate with the core R matrix framework. But that necessarily imposes some performance penalties, such as modifying data in a copy, or having extensions being wed to S4, which can make iterated methods very slow. Other approaches to tackle this problem include the well-known RcppArmadillo package @rcpparmadillo, which makes the use of the Armadillo C++ library @armadillo from within an R package very straightforward. 

<!-- TODO bridge these paragraphs -->

Here we introduce the fmlr package @fmlr, a novel framework for matrix computing with R whose primary concern is performance. It provides numerous matrix and statistics operations for both 32 and 64-bit floating point data, stored on CPU, GPU, or distributed across an MPI cluster, all with a single, unified interface managed by R6 @R6. Additionally, because our interface is entirely novel, we are able to avoid some of the inherent performance penalties imposed by the R matrix interface, including those mentioned above. If accepted, we plan to show the UseR attendee some of the capabilities of this new framework, its syntax, and some example performance benchmarks.


<div id="refs"></div>